{
 "title": "rise",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Block Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of gas used in a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Gas" } },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_total_gas",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total number of transactions in a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_total_txs",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Raw RLP-encoded block size in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_raw_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of failed transactions in a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_total_failed_txs",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total number of reverted transactions in a block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_total_reverted_txs",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Block Building Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Interval between new payload requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_rise_payload_payload_job_interval_sum[1m]) / rate(reth_rise_payload_payload_job_interval_count[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time spent building a new payload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_rise_block_pipeline_build_payload_duration_sum[1m]) / rate(reth_rise_block_pipeline_build_payload_duration_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time budget between the initial payload request to the resolve request",
   "type": "timeseries",
   "description": "Duration between RisePayloadJobGenerator::new_payload_job and RisePayloadJob::resolve calls",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_rise_payload_payload_time_budget_sum[1m]) / rate(reth_rise_payload_payload_time_budget_count[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of account changes in a block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "reth_rise_block_pipeline_block_account_changes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Rise Node",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{container = \"ops-bedrock-l2-1\"}"
    },
    {
     "expr": "{job = \"native-rise-exec\"}"
    }
   ]
  }
 ]
}